# Generated by Django 4.0.3 on 2022-03-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_person_indent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indent_no', models.CharField(max_length=30)),
                ('po_no', models.CharField(max_length=30)),
                ('grn_no', models.CharField(max_length=30)),
                ('issue_no', models.CharField(max_length=30)),
                ('item_name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(max_length=30)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.IntegerField(max_length=30)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gst', models.IntegerField(max_length=30)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Indent',
        ),
    ]
